/* Generated By:JavaCC: Do not edit this line. JavaScriptConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaScriptConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 7;
  /** RegularExpression Id. */
  int VAR = 8;
  /** RegularExpression Id. */
  int LET = 9;
  /** RegularExpression Id. */
  int CONST = 10;
  /** RegularExpression Id. */
  int FUNCTION = 11;
  /** RegularExpression Id. */
  int RETURN = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int DO = 16;
  /** RegularExpression Id. */
  int FOR = 17;
  /** RegularExpression Id. */
  int BREAK = 18;
  /** RegularExpression Id. */
  int CONTINUE = 19;
  /** RegularExpression Id. */
  int SWITCH = 20;
  /** RegularExpression Id. */
  int CASE = 21;
  /** RegularExpression Id. */
  int JS_DEFAULT = 22;
  /** RegularExpression Id. */
  int NEW = 23;
  /** RegularExpression Id. */
  int TYPEOF = 24;
  /** RegularExpression Id. */
  int INSTANCEOF = 25;
  /** RegularExpression Id. */
  int IN = 26;
  /** RegularExpression Id. */
  int OF = 27;
  /** RegularExpression Id. */
  int CLASS = 28;
  /** RegularExpression Id. */
  int EXTENDS = 29;
  /** RegularExpression Id. */
  int THIS = 30;
  /** RegularExpression Id. */
  int SUPER = 31;
  /** RegularExpression Id. */
  int IMPORT = 32;
  /** RegularExpression Id. */
  int EXPORT = 33;
  /** RegularExpression Id. */
  int FROM = 34;
  /** RegularExpression Id. */
  int TRY = 35;
  /** RegularExpression Id. */
  int CATCH = 36;
  /** RegularExpression Id. */
  int FINALLY = 37;
  /** RegularExpression Id. */
  int THROW = 38;
  /** RegularExpression Id. */
  int DELETE = 39;
  /** RegularExpression Id. */
  int VOID = 40;
  /** RegularExpression Id. */
  int TRUE = 41;
  /** RegularExpression Id. */
  int FALSE = 42;
  /** RegularExpression Id. */
  int NULL = 43;
  /** RegularExpression Id. */
  int UNDEFINED = 44;
  /** RegularExpression Id. */
  int NUMBER = 45;
  /** RegularExpression Id. */
  int STRING_DOUBLE = 46;
  /** RegularExpression Id. */
  int STRING_SINGLE = 47;
  /** RegularExpression Id. */
  int TEMPLATE_STR = 48;
  /** RegularExpression Id. */
  int IDENTIFIER = 49;
  /** RegularExpression Id. */
  int STRICT_EQ = 50;
  /** RegularExpression Id. */
  int STRICT_NEQ = 51;
  /** RegularExpression Id. */
  int EQ = 52;
  /** RegularExpression Id. */
  int NEQ = 53;
  /** RegularExpression Id. */
  int PLUSPLUS = 54;
  /** RegularExpression Id. */
  int MINUSMINUS = 55;
  /** RegularExpression Id. */
  int PLUS_ASSIGN = 56;
  /** RegularExpression Id. */
  int MINUS_ASSIGN = 57;
  /** RegularExpression Id. */
  int TIMES_ASSIGN = 58;
  /** RegularExpression Id. */
  int DIV_ASSIGN = 59;
  /** RegularExpression Id. */
  int MOD_ASSIGN = 60;
  /** RegularExpression Id. */
  int AND_ASSIGN = 61;
  /** RegularExpression Id. */
  int OR_ASSIGN = 62;
  /** RegularExpression Id. */
  int LSHIFT = 63;
  /** RegularExpression Id. */
  int RSHIFT = 64;
  /** RegularExpression Id. */
  int URSHIFT = 65;
  /** RegularExpression Id. */
  int LEQ = 66;
  /** RegularExpression Id. */
  int GEQ = 67;
  /** RegularExpression Id. */
  int AND = 68;
  /** RegularExpression Id. */
  int OR = 69;
  /** RegularExpression Id. */
  int NULLCOAL = 70;
  /** RegularExpression Id. */
  int ARROW = 71;
  /** RegularExpression Id. */
  int SPREAD = 72;
  /** RegularExpression Id. */
  int OPT_CHAIN = 73;
  /** RegularExpression Id. */
  int ASSIGN = 74;
  /** RegularExpression Id. */
  int LT = 75;
  /** RegularExpression Id. */
  int GT = 76;
  /** RegularExpression Id. */
  int PLUS = 77;
  /** RegularExpression Id. */
  int MINUS = 78;
  /** RegularExpression Id. */
  int TIMES = 79;
  /** RegularExpression Id. */
  int DIV = 80;
  /** RegularExpression Id. */
  int MOD = 81;
  /** RegularExpression Id. */
  int NOT = 82;
  /** RegularExpression Id. */
  int TILDE = 83;
  /** RegularExpression Id. */
  int AMP = 84;
  /** RegularExpression Id. */
  int PIPE = 85;
  /** RegularExpression Id. */
  int CARET = 86;
  /** RegularExpression Id. */
  int QUESTION = 87;
  /** RegularExpression Id. */
  int COLON = 88;
  /** RegularExpression Id. */
  int SEMICOLON = 89;
  /** RegularExpression Id. */
  int COMMA = 90;
  /** RegularExpression Id. */
  int DOT = 91;
  /** RegularExpression Id. */
  int LPAREN = 92;
  /** RegularExpression Id. */
  int RPAREN = 93;
  /** RegularExpression Id. */
  int LBRACE = 94;
  /** RegularExpression Id. */
  int RBRACE = 95;
  /** RegularExpression Id. */
  int LBRACKET = 96;
  /** RegularExpression Id. */
  int RBRACKET = 97;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\f\"",
    "<LINE_COMMENT>",
    "<BLOCK_COMMENT>",
    "\"var\"",
    "\"let\"",
    "\"const\"",
    "\"function\"",
    "\"return\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"break\"",
    "\"continue\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"new\"",
    "\"typeof\"",
    "\"instanceof\"",
    "\"in\"",
    "\"of\"",
    "\"class\"",
    "\"extends\"",
    "\"this\"",
    "\"super\"",
    "\"import\"",
    "\"export\"",
    "\"from\"",
    "\"try\"",
    "\"catch\"",
    "\"finally\"",
    "\"throw\"",
    "\"delete\"",
    "\"void\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"undefined\"",
    "<NUMBER>",
    "<STRING_DOUBLE>",
    "<STRING_SINGLE>",
    "<TEMPLATE_STR>",
    "<IDENTIFIER>",
    "\"===\"",
    "\"!==\"",
    "\"==\"",
    "\"!=\"",
    "\"++\"",
    "\"--\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&&=\"",
    "\"||=\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"??\"",
    "\"=>\"",
    "\"...\"",
    "\"?.\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"!\"",
    "\"~\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"?\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"constructor\"",
    "\"static\"",
  };

}
