/* Generated By:JavaCC: Do not edit this line. JavaScriptTokenManager.java */
import java.util.*;
import java.io.*;

/** Token Manager. */
public class JavaScriptTokenManager implements JavaScriptConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x800000000000000L) != 0L || (active1 & 0x10000L) != 0L)
            return 30;
         if ((active0 & 0x1fffffffff00L) != 0L || (active1 & 0xc00000000L) != 0L)
         {
            jjmatchedKind = 49;
            return 28;
         }
         return -1;
      case 1:
         if ((active0 & 0x1ffff1fedf00L) != 0L || (active1 & 0xc00000000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 49;
               jjmatchedPos = 1;
            }
            return 28;
         }
         if ((active0 & 0xe012000L) != 0L)
            return 28;
         return -1;
      case 2:
         if ((active0 & 0x800820300L) != 0L)
            return 28;
         if ((active0 & 0x1ff7f37cdc00L) != 0L || (active1 & 0xc00000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 2;
            return 28;
         }
         return -1;
      case 3:
         if ((active0 & 0xb0440204000L) != 0L)
            return 28;
         if ((active0 & 0x14f3b35c9c00L) != 0L || (active1 & 0xc00000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 3;
            return 28;
         }
         return -1;
      case 4:
         if ((active0 & 0x10a323581800L) != 0L || (active1 & 0x800000000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 49;
               jjmatchedPos = 4;
            }
            return 28;
         }
         if ((active0 & 0x45090048400L) != 0L || (active1 & 0x400000000L) != 0L)
            return 28;
         return -1;
      case 5:
         if ((active0 & 0x8301101000L) != 0L)
            return 28;
         if ((active0 & 0x102022480800L) != 0L || (active1 & 0xc00000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 5;
            return 28;
         }
         return -1;
      case 6:
         if ((active0 & 0x2020400000L) != 0L)
            return 28;
         if ((active0 & 0x100002080800L) != 0L || (active1 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 6;
            return 28;
         }
         return -1;
      case 7:
         if ((active0 & 0x100002000000L) != 0L || (active1 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 7;
            return 28;
         }
         if ((active0 & 0x80800L) != 0L)
            return 28;
         return -1;
      case 8:
         if ((active0 & 0x100000000000L) != 0L)
            return 28;
         if ((active0 & 0x2000000L) != 0L || (active1 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 8;
            return 28;
         }
         return -1;
      case 9:
         if ((active0 & 0x2000000L) != 0L)
            return 28;
         if ((active1 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 9;
            return 28;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 82;
         return jjMoveStringLiteralDfa1_0(0x28000000000000L, 0x0L);
      case 37:
         jjmatchedKind = 81;
         return jjMoveStringLiteralDfa1_0(0x1000000000000000L, 0x0L);
      case 38:
         jjmatchedKind = 84;
         return jjMoveStringLiteralDfa1_0(0x2000000000000000L, 0x10L);
      case 40:
         return jjStopAtPos(0, 92);
      case 41:
         return jjStopAtPos(0, 93);
      case 42:
         jjmatchedKind = 79;
         return jjMoveStringLiteralDfa1_0(0x400000000000000L, 0x0L);
      case 43:
         jjmatchedKind = 77;
         return jjMoveStringLiteralDfa1_0(0x140000000000000L, 0x0L);
      case 44:
         return jjStopAtPos(0, 90);
      case 45:
         jjmatchedKind = 78;
         return jjMoveStringLiteralDfa1_0(0x280000000000000L, 0x0L);
      case 46:
         jjmatchedKind = 91;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100L);
      case 47:
         jjmatchedKind = 80;
         return jjMoveStringLiteralDfa1_0(0x800000000000000L, 0x0L);
      case 58:
         return jjStopAtPos(0, 88);
      case 59:
         return jjStopAtPos(0, 89);
      case 60:
         jjmatchedKind = 75;
         return jjMoveStringLiteralDfa1_0(0x8000000000000000L, 0x4L);
      case 61:
         jjmatchedKind = 74;
         return jjMoveStringLiteralDfa1_0(0x14000000000000L, 0x80L);
      case 62:
         jjmatchedKind = 76;
         return jjMoveStringLiteralDfa1_0(0x0L, 0xbL);
      case 63:
         jjmatchedKind = 87;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x240L);
      case 91:
         return jjStopAtPos(0, 96);
      case 93:
         return jjStopAtPos(0, 97);
      case 94:
         return jjStopAtPos(0, 86);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x40000L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x1010280400L, 0x400000000L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x8000410000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x220004000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x42400020800L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x106002000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x200L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x80000800000L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x8000000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x1000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x80100000L, 0x800000000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x24841000000L, 0x0L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x100000000000L, 0x0L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x10000000100L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x8000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 94);
      case 124:
         jjmatchedKind = 85;
         return jjMoveStringLiteralDfa1_0(0x4000000000000000L, 0x20L);
      case 125:
         return jjStopAtPos(0, 95);
      case 126:
         return jjStopAtPos(0, 83);
      default :
         return jjMoveNfa_0(6, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active1 & 0x10L) != 0L)
         {
            jjmatchedKind = 68;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000000000L, active1, 0L);
      case 43:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStopAtPos(1, 54);
         break;
      case 45:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStopAtPos(1, 55);
         break;
      case 46:
         if ((active1 & 0x200L) != 0L)
            return jjStopAtPos(1, 73);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x100L);
      case 60:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStopAtPos(1, 63);
         break;
      case 61:
         if ((active0 & 0x10000000000000L) != 0L)
         {
            jjmatchedKind = 52;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x100000000000000L) != 0L)
            return jjStopAtPos(1, 56);
         else if ((active0 & 0x200000000000000L) != 0L)
            return jjStopAtPos(1, 57);
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStopAtPos(1, 58);
         else if ((active0 & 0x800000000000000L) != 0L)
            return jjStopAtPos(1, 59);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStopAtPos(1, 60);
         else if ((active1 & 0x4L) != 0L)
            return jjStopAtPos(1, 66);
         else if ((active1 & 0x8L) != 0L)
            return jjStopAtPos(1, 67);
         return jjMoveStringLiteralDfa2_0(active0, 0xc000000000000L, active1, 0L);
      case 62:
         if ((active1 & 0x1L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x80L) != 0L)
            return jjStopAtPos(1, 71);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x2L);
      case 63:
         if ((active1 & 0x40L) != 0L)
            return jjStopAtPos(1, 70);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x41000200100L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000c01200L, active1, 0L);
      case 102:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(1, 13, 28);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(1, 27, 28);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x4040008000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x10004000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000L, active1, 0L);
      case 110:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x100002000000L, active1, 0L);
      case 111:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(1, 16, 28);
         return jjMoveStringLiteralDfa2_0(active0, 0x100000a0400L, active1, 0x400000000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x20c00040000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x800000000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x80080000800L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000L, active1, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x220000000L, active1, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L, active1, 0L);
      case 124:
         if ((active1 & 0x20L) != 0L)
         {
            jjmatchedKind = 69;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 46:
         if ((active1 & 0x100L) != 0L)
            return jjStopAtPos(2, 72);
         break;
      case 61:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStopAtPos(2, 50);
         else if ((active0 & 0x8000000000000L) != 0L)
            return jjStopAtPos(2, 51);
         else if ((active0 & 0x2000000000000000L) != 0L)
            return jjStopAtPos(2, 61);
         else if ((active0 & 0x4000000000000000L) != 0L)
            return jjStopAtPos(2, 62);
         break;
      case 62:
         if ((active1 & 0x2L) != 0L)
            return jjStopAtPos(2, 65);
         break;
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L, active1, 0x800000000L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000L, active1, 0L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x10040108000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0xc8000000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000080c00L, active1, 0x400000000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x381000000L, active1, 0L);
      case 114:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(2, 8, 28);
         else if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(2, 17, 28);
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x2204000L, active1, 0L);
      case 116:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 9, 28);
         return jjMoveStringLiteralDfa3_0(active0, 0x1020001000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000000L, active1, 0L);
      case 119:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(2, 23, 28);
         break;
      case 121:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(2, 35, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000440000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000800L, active1, 0L);
      case 100:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 40, 28);
         break;
      case 101:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(3, 14, 28);
         else if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(3, 21, 28);
         else if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 41, 28);
         return jjMoveStringLiteralDfa4_0(active0, 0x1080a1000000L, active1, 0L);
      case 108:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 43, 28);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L, active1, 0L);
      case 109:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(3, 34, 28);
         break;
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x4300000000L, active1, 0L);
      case 115:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 30, 28);
         return jjMoveStringLiteralDfa4_0(active0, 0x40010000400L, active1, 0x400000000L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x2180000L, active1, 0x800000000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000L, active1, 0L);
      case 101:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(4, 15, 28);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 42, 28);
         break;
      case 102:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000L, active1, 0L);
      case 104:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 36, 28);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000L, active1, 0x800000000L);
      case 107:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(4, 18, 28);
         break;
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000L, active1, 0L);
      case 114:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(4, 31, 28);
         return jjMoveStringLiteralDfa5_0(active0, 0x300001000L, active1, 0L);
      case 115:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(4, 28, 28);
         break;
      case 116:
         if ((active0 & 0x400L) != 0L)
         {
            jjmatchedKind = 10;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000800L, active1, 0x400000000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000L, active1, 0L);
      case 119:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 38, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 99:
         if ((active1 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(5, 49, 28);
         break;
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000L, active1, 0L);
      case 101:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 39, 28);
         break;
      case 102:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(5, 24, 28);
         break;
      case 104:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(5, 20, 28);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000800L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000400000L, active1, 0L);
      case 110:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(5, 12, 28);
         return jjMoveStringLiteralDfa6_0(active0, 0x2080000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x400000000L);
      case 116:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(5, 32, 28);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(5, 33, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x800L, active1, 0L);
      case 115:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(6, 29, 28);
         break;
      case 116:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(6, 22, 28);
         break;
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000L, active1, 0x400000000L);
      case 121:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 37, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1);
      return 7;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x400000000L);
      case 101:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(7, 19, 28);
         return jjMoveStringLiteralDfa8_0(active0, 0x100002000000L, active1, 0L);
      case 110:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(7, 11, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1);
      return 8;
   }
   switch(curChar)
   {
      case 100:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 44, 28);
         break;
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x2000000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x400000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1);
      return 9;
   }
   switch(curChar)
   {
      case 102:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(9, 25, 28);
         break;
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x400000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, 0L, active1);
      return 10;
   }
   switch(curChar)
   {
      case 114:
         if ((active1 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(10, 49, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, 0L, active1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   //int[] nextStates; // not used
   int startsAt = 0;
   jjnewStateCnt = 41;
   int i = 1;
   jjstateSet[0] = startState;
   //int j; // not used
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 30:
                  if (curChar == 42)
                     jjCheckNAddStates(0, 2);
                  else if (curChar == 47)
                  {
                     if (kind > 6)
                        kind = 6;
                     jjCheckNAddStates(3, 5);
                  }
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 45)
                        kind = 45;
                     jjCheckNAddStates(6, 8);
                  }
                  else if (curChar == 47)
                     jjAddStates(9, 10);
                  else if (curChar == 36)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(28);
                  }
                  else if (curChar == 39)
                     jjCheckNAddStates(11, 13);
                  else if (curChar == 34)
                     jjCheckNAddStates(14, 16);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAddStates(6, 8);
                  break;
               case 1:
                  if (curChar == 46)
                     jjCheckNAdd(2);
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAddTwoStates(2, 3);
                  break;
               case 4:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(5);
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAdd(5);
                  break;
               case 7:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(14, 16);
                  break;
               case 9:
                  jjCheckNAddStates(14, 16);
                  break;
               case 10:
                  if (curChar == 34 && kind > 46)
                     kind = 46;
                  break;
               case 11:
                  if (curChar == 39)
                     jjCheckNAddStates(11, 13);
                  break;
               case 12:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     jjCheckNAddStates(11, 13);
                  break;
               case 14:
                  jjCheckNAddStates(11, 13);
                  break;
               case 15:
                  if (curChar == 39 && kind > 47)
                     kind = 47;
                  break;
               case 17:
                  if ((0xffffffefffffffffL & l) != 0L)
                     jjAddStates(17, 20);
                  break;
               case 23:
                  jjAddStates(21, 22);
                  break;
               case 25:
                  if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 27:
                  if (curChar != 36)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(28);
                  break;
               case 28:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(28);
                  break;
               case 29:
                  if (curChar == 47)
                     jjAddStates(9, 10);
                  break;
               case 31:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjCheckNAddStates(3, 5);
                  break;
               case 32:
                  if ((0x2400L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 33:
                  if (curChar == 10 && kind > 6)
                     kind = 6;
                  break;
               case 34:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if (curChar == 42)
                     jjCheckNAddStates(0, 2);
                  break;
               case 36:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 37:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 39:
                  if (curChar == 47 && kind > 7)
                     kind = 7;
                  break;
               case 40:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 6:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(28);
                  }
                  else if (curChar == 96)
                     jjCheckNAddStates(17, 20);
                  break;
               case 3:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(23, 24);
                  break;
               case 7:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(14, 16);
                  break;
               case 8:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 9:
                  jjCheckNAddStates(14, 16);
                  break;
               case 12:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(11, 13);
                  break;
               case 13:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 14:
                  jjCheckNAddStates(11, 13);
                  break;
               case 16:
                  if (curChar == 96)
                     jjCheckNAddStates(17, 20);
                  break;
               case 17:
                  if ((0xfffffffeefffffffL & l) != 0L)
                     jjCheckNAddStates(17, 20);
                  break;
               case 18:
                  if (curChar == 93)
                     jjCheckNAddStates(17, 20);
                  break;
               case 19:
                  if (curChar == 91)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 126)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 123)
                     jjCheckNAddTwoStates(23, 24);
                  break;
               case 23:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(23, 24);
                  break;
               case 24:
                  if (curChar == 125)
                     jjCheckNAddStates(17, 20);
                  break;
               case 26:
                  if (curChar == 96 && kind > 48)
                     kind = 48;
                  break;
               case 27:
               case 28:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(28);
                  break;
               case 31:
                  if (kind > 6)
                     kind = 6;
                  jjAddStates(3, 5);
                  break;
               case 36:
               case 38:
                  jjCheckNAddStates(0, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 7:
               case 9:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddStates(14, 16);
                  break;
               case 12:
               case 14:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddStates(11, 13);
                  break;
               case 17:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(17, 20);
                  break;
               case 23:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(21, 22);
                  break;
               case 31:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjAddStates(3, 5);
                  break;
               case 36:
               case 38:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 41 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   36, 37, 40, 31, 32, 34, 0, 1, 3, 30, 35, 12, 13, 15, 7, 8, 
   10, 17, 21, 25, 26, 23, 24, 4, 5, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, "\166\141\162", "\154\145\164", 
"\143\157\156\163\164", "\146\165\156\143\164\151\157\156", "\162\145\164\165\162\156", "\151\146", 
"\145\154\163\145", "\167\150\151\154\145", "\144\157", "\146\157\162", "\142\162\145\141\153", 
"\143\157\156\164\151\156\165\145", "\163\167\151\164\143\150", "\143\141\163\145", 
"\144\145\146\141\165\154\164", "\156\145\167", "\164\171\160\145\157\146", 
"\151\156\163\164\141\156\143\145\157\146", "\151\156", "\157\146", "\143\154\141\163\163", 
"\145\170\164\145\156\144\163", "\164\150\151\163", "\163\165\160\145\162", "\151\155\160\157\162\164", 
"\145\170\160\157\162\164", "\146\162\157\155", "\164\162\171", "\143\141\164\143\150", 
"\146\151\156\141\154\154\171", "\164\150\162\157\167", "\144\145\154\145\164\145", "\166\157\151\144", 
"\164\162\165\145", "\146\141\154\163\145", "\156\165\154\154", 
"\165\156\144\145\146\151\156\145\144", null, null, null, null, null, "\75\75\75", "\41\75\75", "\75\75", "\41\75", 
"\53\53", "\55\55", "\53\75", "\55\75", "\52\75", "\57\75", "\45\75", "\46\46\75", 
"\174\174\75", "\74\74", "\76\76", "\76\76\76", "\74\75", "\76\75", "\46\46", "\174\174", 
"\77\77", "\75\76", "\56\56\56", "\77\56", "\75", "\74", "\76", "\53", "\55", "\52", 
"\57", "\45", "\41", "\176", "\46", "\174", "\136", "\77", "\72", "\73", "\54", 
"\56", "\50", "\51", "\173", "\175", "\133", "\135", 
"\143\157\156\163\164\162\165\143\164\157\162", "\163\164\141\164\151\143", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0xffffffffffffff01L, 0xfffffffffL, 
};
static final long[] jjtoSkip = {
   0xfeL, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[41];
private final int[] jjstateSet = new int[82];
protected char curChar;
/** Constructor. */
public JavaScriptTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public JavaScriptTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 41; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String tokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   tokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, tokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  //int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
