/* Generated By:JavaCC: Do not edit this line. JavaScript.java */
import java.util.*;
import java.io.*;

public class JavaScript implements JavaScriptConstants {

    // =============================================
    // AN�?LISE SEMÂNTICA - Tabela de Símbolos
    // =============================================

    // Pilha de escopos (cada escopo eh um Map nome->tipo)
    private Deque scopeStack = new ArrayDeque();
    private List errosSemânticos = new ArrayList();
    private List avisosSemânticos = new ArrayList();
    private int erros = 0;

    private static final Set GLOBALS = new HashSet(Arrays.asList(new String[]{
        "console", "Math", "parseInt", "parseFloat", "isNaN", "isFinite",
        "String", "Number", "Boolean", "Array", "Object", "JSON",
        "undefined", "null", "true", "false", "NaN", "Infinity",
        "setTimeout", "setInterval", "clearTimeout", "clearInterval",
        "alert", "prompt", "confirm", "document", "window", "process"
    }));

    /** Entra em um novo escopo */
    private void enterScope() {
        scopeStack.push(new LinkedHashMap());
    }

    /** Sai do escopo atual */
    private void exitScope() {
        if (!scopeStack.isEmpty()) {
            scopeStack.pop();
        }
    }

    /** Declara uma variável no escopo atual */
    private void declareVar(String name, String kind) {
        if (scopeStack.isEmpty()) return;
        Map current = (Map) scopeStack.peek();
        if (current.containsKey(name)) {
            String prev = (String) current.get(name);
            if (prev.equals("const") || kind.equals("const")) {
                erroSemantico("Redeclara\u00c3\u00a7\u00c3\u00a3o inv\u00c3\u00a1lida da vari\u00c3\u00a1vel '" + name + "' (declarada como '" + prev + "')");
            } else {
                avisoSemantico("Vari\u00c3\u00a1vel '" + name + "' j\u00c3\u00a1 declarada neste escopo como '" + prev + "'");
            }
        }
        current.put(name, kind);
    }

    /** Verifica se uma variável está declarada em algum escopo */
    private boolean isVarDeclared(String name) {
        for (Object obj : scopeStack) {
            Map scope = (Map) obj;
            if (scope.containsKey(name)) return true;
        }
        return false;
    }

    /** Verifica uso de variável e registra erro se não declarada */
    private void checkVarUse(String name) {
        if (!GLOBALS.contains(name) && !isVarDeclared(name)) {
            erroSemantico("Vari\u00c3\u00a1vel '" + name + "' utilizada sem declara\u00c3\u00a7\u00c3\u00a3o");
        }
    }

    private void erroSemantico(String msg) {
        erros++;
        errosSemânticos.add("[ERRO SEM\u00c3\u201aNTICO] " + msg);
    }

    private void avisoSemantico(String msg) {
        avisosSemânticos.add("[AVISO SEM\u00c3\u201aNTICO] " + msg);
    }

    private void imprimirResultados() {
        System.out.println("\n========================================");
        System.out.println("     RESULTADO DA AN\u00c3\ufffdLISE");
        System.out.println("========================================");

        if (!avisosSemânticos.isEmpty()) {
            System.out.println("\n--- Avisos ---");
            for (Object a : avisosSemânticos) System.out.println(a);
        }

        if (errosSemânticos.isEmpty()) {
            System.out.println("\n[OK] An\u00c3\u00a1lise sem\u00c3\u00a2ntica: nenhum erro encontrado.");
        } else {
            System.out.println("\n--- Erros Sem\u00c3\u00a2nticos ---");
            for (Object e : errosSemânticos) System.out.println(e);
        }

        System.out.println("\n--- Resumo ---");
        System.out.println("Erros sem\u00c3\u00a2nticos : " + erros);
        System.out.println("Avisos           : " + avisosSemânticos.size());
        System.out.println("========================================\n");
    }

    // =============================================
    // MAIN
    // =============================================

    public static void main(String[] args) throws Exception {
        InputStream input;
        String filename = "";

        if (args.length > 0) {
            filename = args[0];
            input = new FileInputStream(filename);
            System.out.println("Compilando arquivo: " + filename);
        } else {
            System.out.println("Uso: java JavaScript <arquivo.js>");
            System.out.println("Usando entrada padr\u00c3\u00a3o (stdin)...");
            input = System.in;
        }

        JavaScript parser = new JavaScript(input);
        try {
            parser.enterScope(); // escopo global
            parser.Program();
            parser.exitScope();
            System.out.println("\n[OK] An\u00c3\u00a1lise l\u00c3\u00a9xica e sint\u00c3\u00a1tica conclu\u00c3\u00adda sem erros.");
            parser.imprimirResultados();
        } catch (ParseException e) {
            System.err.println("\n[ERRO SINT\u00c3\ufffdTICO] " + e.getMessage());
            parser.imprimirResultados();
            System.exit(1);
        } catch (TokenMgrError e) {
            System.err.println("\n[ERRO L\u00c3\u2030XICO] " + e.getMessage());
            System.exit(1);
        }
    }

// =============================================
// AN�?LISE SINT�?TICA - Gramática
// =============================================

/** Programa: sequência de statements */
  final public void Program() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VAR:
      case LET:
      case CONST:
      case FUNCTION:
      case RETURN:
      case IF:
      case WHILE:
      case DO:
      case FOR:
      case BREAK:
      case CONTINUE:
      case SWITCH:
      case NEW:
      case TYPEOF:
      case CLASS:
      case THIS:
      case SUPER:
      case TRY:
      case THROW:
      case DELETE:
      case VOID:
      case TRUE:
      case FALSE:
      case NULL:
      case UNDEFINED:
      case NUMBER:
      case STRING_DOUBLE:
      case STRING_SINGLE:
      case TEMPLATE_STR:
      case IDENTIFIER:
      case PLUSPLUS:
      case MINUSMINUS:
      case PLUS:
      case MINUS:
      case NOT:
      case TILDE:
      case SEMICOLON:
      case LPAREN:
      case LBRACE:
      case LBRACKET:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      Statement();
    }
    jj_consume_token(0);
  }

/** Statement genérico */
  final public void Statement() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LBRACE:
      Block();
      break;
    case VAR:
    case LET:
    case CONST:
      VarDeclaration();
      break;
    default:
      jj_la1[1] = jj_gen;
      if (jj_2_1(2147483647)) {
        FunctionDeclaration();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CLASS:
          ClassDeclaration();
          break;
        case IF:
          IfStatement();
          break;
        case WHILE:
          WhileStatement();
          break;
        case DO:
          DoWhileStatement();
          break;
        case FOR:
          ForStatement();
          break;
        case SWITCH:
          SwitchStatement();
          break;
        case TRY:
          TryCatchStatement();
          break;
        case RETURN:
          ReturnStatement();
          break;
        case BREAK:
          BreakStatement();
          break;
        case CONTINUE:
          ContinueStatement();
          break;
        case THROW:
          ThrowStatement();
          break;
        case SEMICOLON:
          EmptyStatement();
          break;
        case FUNCTION:
        case NEW:
        case TYPEOF:
        case THIS:
        case SUPER:
        case DELETE:
        case VOID:
        case TRUE:
        case FALSE:
        case NULL:
        case UNDEFINED:
        case NUMBER:
        case STRING_DOUBLE:
        case STRING_SINGLE:
        case TEMPLATE_STR:
        case IDENTIFIER:
        case PLUSPLUS:
        case MINUSMINUS:
        case PLUS:
        case MINUS:
        case NOT:
        case TILDE:
        case LPAREN:
        case LBRACE:
        case LBRACKET:
          ExpressionStatement();
          break;
        default:
          jj_la1[2] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
  }

/** Bloco { ... } */
  final public void Block() throws ParseException {
    jj_consume_token(LBRACE);
      enterScope();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VAR:
      case LET:
      case CONST:
      case FUNCTION:
      case RETURN:
      case IF:
      case WHILE:
      case DO:
      case FOR:
      case BREAK:
      case CONTINUE:
      case SWITCH:
      case NEW:
      case TYPEOF:
      case CLASS:
      case THIS:
      case SUPER:
      case TRY:
      case THROW:
      case DELETE:
      case VOID:
      case TRUE:
      case FALSE:
      case NULL:
      case UNDEFINED:
      case NUMBER:
      case STRING_DOUBLE:
      case STRING_SINGLE:
      case TEMPLATE_STR:
      case IDENTIFIER:
      case PLUSPLUS:
      case MINUSMINUS:
      case PLUS:
      case MINUS:
      case NOT:
      case TILDE:
      case SEMICOLON:
      case LPAREN:
      case LBRACE:
      case LBRACKET:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      Statement();
    }
    jj_consume_token(RBRACE);
      exitScope();
  }

/** Bloco sem criar novo escopo (para function body) */
  final public void FunctionBlock() throws ParseException {
    jj_consume_token(LBRACE);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VAR:
      case LET:
      case CONST:
      case FUNCTION:
      case RETURN:
      case IF:
      case WHILE:
      case DO:
      case FOR:
      case BREAK:
      case CONTINUE:
      case SWITCH:
      case NEW:
      case TYPEOF:
      case CLASS:
      case THIS:
      case SUPER:
      case TRY:
      case THROW:
      case DELETE:
      case VOID:
      case TRUE:
      case FALSE:
      case NULL:
      case UNDEFINED:
      case NUMBER:
      case STRING_DOUBLE:
      case STRING_SINGLE:
      case TEMPLATE_STR:
      case IDENTIFIER:
      case PLUSPLUS:
      case MINUSMINUS:
      case PLUS:
      case MINUS:
      case NOT:
      case TILDE:
      case SEMICOLON:
      case LPAREN:
      case LBRACE:
      case LBRACKET:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      Statement();
    }
    jj_consume_token(RBRACE);
  }

/** ; vazio */
  final public void EmptyStatement() throws ParseException {
    jj_consume_token(SEMICOLON);
  }

// ---- Declarações de variáveis ----
  final public void VarDeclaration() throws ParseException {
  Token kind;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VAR:
      kind = jj_consume_token(VAR);
      break;
    case LET:
      kind = jj_consume_token(LET);
      break;
    case CONST:
      kind = jj_consume_token(CONST);
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    VarDeclaratorList(kind.image);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SEMICOLON:
      jj_consume_token(SEMICOLON);
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
  }

  final public void VarDeclaratorList(String kind) throws ParseException {
    VarDeclarator(kind);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_4;
      }
      jj_consume_token(COMMA);
      VarDeclarator(kind);
    }
  }

  final public void VarDeclarator(String kind) throws ParseException {
  Token t;
    t = jj_consume_token(IDENTIFIER);
      declareVar(t.image, kind);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASSIGN:
      jj_consume_token(ASSIGN);
      AssignmentExpression();
      break;
    default:
      jj_la1[8] = jj_gen;
      ;
    }
  }

// ---- Funções ----
  final public void FunctionDeclaration() throws ParseException {
  Token t;
    jj_consume_token(FUNCTION);
    t = jj_consume_token(IDENTIFIER);
      declareVar(t.image, "function");
    jj_consume_token(LPAREN);
      enterScope();
    FormalParameters();
    jj_consume_token(RPAREN);
    FunctionBlock();
      exitScope();
  }

  final public void FormalParameters() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
    case SPREAD:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SPREAD:
        jj_consume_token(SPREAD);
        break;
      default:
        jj_la1[9] = jj_gen;
        ;
      }
      t = jj_consume_token(IDENTIFIER);
          declareVar(t.image, "param");
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ASSIGN:
        jj_consume_token(ASSIGN);
        AssignmentExpression();
        break;
      default:
        jj_la1[10] = jj_gen;
        ;
      }
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[11] = jj_gen;
          break label_5;
        }
        jj_consume_token(COMMA);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SPREAD:
          jj_consume_token(SPREAD);
          break;
        default:
          jj_la1[12] = jj_gen;
          ;
        }
        t = jj_consume_token(IDENTIFIER);
              declareVar(t.image, "param");
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ASSIGN:
          jj_consume_token(ASSIGN);
          AssignmentExpression();
          break;
        default:
          jj_la1[13] = jj_gen;
          ;
        }
      }
      break;
    default:
      jj_la1[14] = jj_gen;
      ;
    }
  }

// ---- Classe ----
  final public void ClassDeclaration() throws ParseException {
  Token t;
    jj_consume_token(CLASS);
    t = jj_consume_token(IDENTIFIER);
      declareVar(t.image, "class");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EXTENDS:
      jj_consume_token(EXTENDS);
      Expression();
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
    jj_consume_token(LBRACE);
      enterScope();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
      case 98:
      case 99:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_6;
      }
      ClassMember();
    }
    jj_consume_token(RBRACE);
      exitScope();
  }

  final public void ClassMember() throws ParseException {
  Token t;
    if (jj_2_2(3)) {

    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 98:
      jj_consume_token(98);
      jj_consume_token(LPAREN);
          enterScope();
      FormalParameters();
      jj_consume_token(RPAREN);
      FunctionBlock();
          exitScope();
      break;
    case IDENTIFIER:
    case 99:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 99:
        jj_consume_token(99);
        break;
      default:
        jj_la1[17] = jj_gen;
        ;
      }
      t = jj_consume_token(IDENTIFIER);
      jj_consume_token(LPAREN);
          enterScope();
      FormalParameters();
      jj_consume_token(RPAREN);
      FunctionBlock();
          exitScope();
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

// ---- Controle de fluxo ----
  final public void IfStatement() throws ParseException {
    jj_consume_token(IF);
    jj_consume_token(LPAREN);
    Expression();
    jj_consume_token(RPAREN);
    Statement();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
      Statement();
      break;
    default:
      jj_la1[19] = jj_gen;
      ;
    }
  }

  final public void WhileStatement() throws ParseException {
    jj_consume_token(WHILE);
    jj_consume_token(LPAREN);
    Expression();
    jj_consume_token(RPAREN);
    Statement();
  }

  final public void DoWhileStatement() throws ParseException {
    jj_consume_token(DO);
    Statement();
    jj_consume_token(WHILE);
    jj_consume_token(LPAREN);
    Expression();
    jj_consume_token(RPAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SEMICOLON:
      jj_consume_token(SEMICOLON);
      break;
    default:
      jj_la1[20] = jj_gen;
      ;
    }
  }

  final public void ForStatement() throws ParseException {
  Token t;
    jj_consume_token(FOR);
    jj_consume_token(LPAREN);
      enterScope();
    if (jj_2_3(2147483647)) {
      VarDeclarationInFor();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IN:
        jj_consume_token(IN);
        break;
      case OF:
        jj_consume_token(OF);
        break;
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Expression();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VAR:
      case LET:
      case CONST:
      case FUNCTION:
      case NEW:
      case TYPEOF:
      case THIS:
      case SUPER:
      case DELETE:
      case VOID:
      case TRUE:
      case FALSE:
      case NULL:
      case UNDEFINED:
      case NUMBER:
      case STRING_DOUBLE:
      case STRING_SINGLE:
      case TEMPLATE_STR:
      case IDENTIFIER:
      case PLUSPLUS:
      case MINUSMINUS:
      case PLUS:
      case MINUS:
      case NOT:
      case TILDE:
      case SEMICOLON:
      case LPAREN:
      case LBRACE:
      case LBRACKET:
        ForInit();
        jj_consume_token(SEMICOLON);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case FUNCTION:
        case NEW:
        case TYPEOF:
        case THIS:
        case SUPER:
        case DELETE:
        case VOID:
        case TRUE:
        case FALSE:
        case NULL:
        case UNDEFINED:
        case NUMBER:
        case STRING_DOUBLE:
        case STRING_SINGLE:
        case TEMPLATE_STR:
        case IDENTIFIER:
        case PLUSPLUS:
        case MINUSMINUS:
        case PLUS:
        case MINUS:
        case NOT:
        case TILDE:
        case LPAREN:
        case LBRACE:
        case LBRACKET:
          Expression();
          break;
        default:
          jj_la1[22] = jj_gen;
          ;
        }
        jj_consume_token(SEMICOLON);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case FUNCTION:
        case NEW:
        case TYPEOF:
        case THIS:
        case SUPER:
        case DELETE:
        case VOID:
        case TRUE:
        case FALSE:
        case NULL:
        case UNDEFINED:
        case NUMBER:
        case STRING_DOUBLE:
        case STRING_SINGLE:
        case TEMPLATE_STR:
        case IDENTIFIER:
        case PLUSPLUS:
        case MINUSMINUS:
        case PLUS:
        case MINUS:
        case NOT:
        case TILDE:
        case LPAREN:
        case LBRACE:
        case LBRACKET:
          Expression();
          break;
        default:
          jj_la1[23] = jj_gen;
          ;
        }
        break;
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(RPAREN);
    Statement();
      exitScope();
  }

  final public void VarDeclarationInFor() throws ParseException {
  Token kind; Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VAR:
      kind = jj_consume_token(VAR);
      break;
    case LET:
      kind = jj_consume_token(LET);
      break;
    case CONST:
      kind = jj_consume_token(CONST);
      break;
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    t = jj_consume_token(IDENTIFIER);
      declareVar(t.image, kind.image);
  }

  final public void VarDeclarationNoSemi() throws ParseException {
  Token kind;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VAR:
      kind = jj_consume_token(VAR);
      break;
    case LET:
      kind = jj_consume_token(LET);
      break;
    case CONST:
      kind = jj_consume_token(CONST);
      break;
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    VarDeclaratorList(kind.image);
  }

  final public void ForInit() throws ParseException {
    if (jj_2_4(2147483647)) {
      VarDeclarationNoSemi();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FUNCTION:
      case NEW:
      case TYPEOF:
      case THIS:
      case SUPER:
      case DELETE:
      case VOID:
      case TRUE:
      case FALSE:
      case NULL:
      case UNDEFINED:
      case NUMBER:
      case STRING_DOUBLE:
      case STRING_SINGLE:
      case TEMPLATE_STR:
      case IDENTIFIER:
      case PLUSPLUS:
      case MINUSMINUS:
      case PLUS:
      case MINUS:
      case NOT:
      case TILDE:
      case LPAREN:
      case LBRACE:
      case LBRACKET:
        ExpressionList();
        break;
      default:
        jj_la1[27] = jj_gen;
        ;
      }
    }
  }

  final public void SwitchStatement() throws ParseException {
    jj_consume_token(SWITCH);
    jj_consume_token(LPAREN);
    Expression();
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
      enterScope();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CASE:
        ;
        break;
      default:
        jj_la1[28] = jj_gen;
        break label_7;
      }
      SwitchCase();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case JS_DEFAULT:
      DefaultCase();
      break;
    default:
      jj_la1[29] = jj_gen;
      ;
    }
    jj_consume_token(RBRACE);
      exitScope();
  }

  final public void SwitchCase() throws ParseException {
    jj_consume_token(CASE);
    Expression();
    jj_consume_token(COLON);
    label_8:
    while (true) {
      if (jj_2_5(2)) {
        ;
      } else {
        break label_8;
      }
      Statement();
    }
  }

  final public void DefaultCase() throws ParseException {
    jj_consume_token(JS_DEFAULT);
    jj_consume_token(COLON);
    label_9:
    while (true) {
      if (jj_2_6(2)) {
        ;
      } else {
        break label_9;
      }
      Statement();
    }
  }

  final public void TryCatchStatement() throws ParseException {
  Token t;
    jj_consume_token(TRY);
    Block();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CATCH:
      jj_consume_token(CATCH);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
        jj_consume_token(LPAREN);
        t = jj_consume_token(IDENTIFIER);
              enterScope(); declareVar(t.image, "catch");
        jj_consume_token(RPAREN);
        break;
      default:
        jj_la1[30] = jj_gen;
        ;
      }
      Block();
          if (!scopeStack.isEmpty()) exitScope();
      break;
    default:
      jj_la1[31] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FINALLY:
      jj_consume_token(FINALLY);
      Block();
      break;
    default:
      jj_la1[32] = jj_gen;
      ;
    }
  }

  final public void ReturnStatement() throws ParseException {
    jj_consume_token(RETURN);
    if (jj_2_7(2)) {
      Expression();
    } else {
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SEMICOLON:
      jj_consume_token(SEMICOLON);
      break;
    default:
      jj_la1[33] = jj_gen;
      ;
    }
  }

  final public void BreakStatement() throws ParseException {
    jj_consume_token(BREAK);
    if (jj_2_8(2147483647)) {
      jj_consume_token(IDENTIFIER);
    } else {
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SEMICOLON:
      jj_consume_token(SEMICOLON);
      break;
    default:
      jj_la1[34] = jj_gen;
      ;
    }
  }

  final public void ContinueStatement() throws ParseException {
    jj_consume_token(CONTINUE);
    if (jj_2_9(2147483647)) {
      jj_consume_token(IDENTIFIER);
    } else {
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SEMICOLON:
      jj_consume_token(SEMICOLON);
      break;
    default:
      jj_la1[35] = jj_gen;
      ;
    }
  }

  final public void ThrowStatement() throws ParseException {
    jj_consume_token(THROW);
    Expression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SEMICOLON:
      jj_consume_token(SEMICOLON);
      break;
    default:
      jj_la1[36] = jj_gen;
      ;
    }
  }

  final public void ExpressionStatement() throws ParseException {
    ExpressionList();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SEMICOLON:
      jj_consume_token(SEMICOLON);
      break;
    default:
      jj_la1[37] = jj_gen;
      ;
    }
  }

  final public void ExpressionList() throws ParseException {
    Expression();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[38] = jj_gen;
        break label_10;
      }
      jj_consume_token(COMMA);
      Expression();
    }
  }

// =============================================
// EXPRESSÕES
// =============================================
  final public void Expression() throws ParseException {
    AssignmentExpression();
  }

  final public void AssignmentExpression() throws ParseException {
    if (jj_2_10(2147483647)) {
      ArrowFunction();
    } else if (jj_2_11(2147483647)) {
      LeftHandSideExpression();
      AssignOp();
      AssignmentExpression();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FUNCTION:
      case NEW:
      case TYPEOF:
      case THIS:
      case SUPER:
      case DELETE:
      case VOID:
      case TRUE:
      case FALSE:
      case NULL:
      case UNDEFINED:
      case NUMBER:
      case STRING_DOUBLE:
      case STRING_SINGLE:
      case TEMPLATE_STR:
      case IDENTIFIER:
      case PLUSPLUS:
      case MINUSMINUS:
      case PLUS:
      case MINUS:
      case NOT:
      case TILDE:
      case LPAREN:
      case LBRACE:
      case LBRACKET:
        ConditionalExpression();
        break;
      default:
        jj_la1[39] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void ArrowFunctionParams() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      jj_consume_token(IDENTIFIER);
      break;
    case LPAREN:
      jj_consume_token(LPAREN);
      FormalParameters();
      jj_consume_token(RPAREN);
      break;
    default:
      jj_la1[40] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void ArrowFunction() throws ParseException {
      enterScope();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      jj_consume_token(IDENTIFIER);
      break;
    case LPAREN:
      jj_consume_token(LPAREN);
      FormalParameters();
      jj_consume_token(RPAREN);
      break;
    default:
      jj_la1[41] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(ARROW);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LBRACE:
      FunctionBlock();
      break;
    case FUNCTION:
    case NEW:
    case TYPEOF:
    case THIS:
    case SUPER:
    case DELETE:
    case VOID:
    case TRUE:
    case FALSE:
    case NULL:
    case UNDEFINED:
    case NUMBER:
    case STRING_DOUBLE:
    case STRING_SINGLE:
    case TEMPLATE_STR:
    case IDENTIFIER:
    case PLUSPLUS:
    case MINUSMINUS:
    case PLUS:
    case MINUS:
    case NOT:
    case TILDE:
    case LPAREN:
    case LBRACKET:
      AssignmentExpression();
      break;
    default:
      jj_la1[42] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      exitScope();
  }

  final public void AssignOp() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASSIGN:
      jj_consume_token(ASSIGN);
      break;
    case PLUS_ASSIGN:
      jj_consume_token(PLUS_ASSIGN);
      break;
    case MINUS_ASSIGN:
      jj_consume_token(MINUS_ASSIGN);
      break;
    case TIMES_ASSIGN:
      jj_consume_token(TIMES_ASSIGN);
      break;
    case DIV_ASSIGN:
      jj_consume_token(DIV_ASSIGN);
      break;
    case MOD_ASSIGN:
      jj_consume_token(MOD_ASSIGN);
      break;
    case AND_ASSIGN:
      jj_consume_token(AND_ASSIGN);
      break;
    case OR_ASSIGN:
      jj_consume_token(OR_ASSIGN);
      break;
    default:
      jj_la1[43] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void ConditionalExpression() throws ParseException {
    LogicalOrExpression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case QUESTION:
      jj_consume_token(QUESTION);
      AssignmentExpression();
      jj_consume_token(COLON);
      AssignmentExpression();
      break;
    default:
      jj_la1[44] = jj_gen;
      ;
    }
  }

  final public void LogicalOrExpression() throws ParseException {
    LogicalAndExpression();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
      case NULLCOAL:
        ;
        break;
      default:
        jj_la1[45] = jj_gen;
        break label_11;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
        jj_consume_token(OR);
        break;
      case NULLCOAL:
        jj_consume_token(NULLCOAL);
        break;
      default:
        jj_la1[46] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      LogicalAndExpression();
    }
  }

  final public void LogicalAndExpression() throws ParseException {
    BitwiseOrExpression();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        ;
        break;
      default:
        jj_la1[47] = jj_gen;
        break label_12;
      }
      jj_consume_token(AND);
      BitwiseOrExpression();
    }
  }

  final public void BitwiseOrExpression() throws ParseException {
    BitwiseXorExpression();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PIPE:
        ;
        break;
      default:
        jj_la1[48] = jj_gen;
        break label_13;
      }
      jj_consume_token(PIPE);
      BitwiseXorExpression();
    }
  }

  final public void BitwiseXorExpression() throws ParseException {
    BitwiseAndExpression();
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CARET:
        ;
        break;
      default:
        jj_la1[49] = jj_gen;
        break label_14;
      }
      jj_consume_token(CARET);
      BitwiseAndExpression();
    }
  }

  final public void BitwiseAndExpression() throws ParseException {
    EqualityExpression();
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AMP:
        ;
        break;
      default:
        jj_la1[50] = jj_gen;
        break label_15;
      }
      jj_consume_token(AMP);
      EqualityExpression();
    }
  }

  final public void EqualityExpression() throws ParseException {
    RelationalExpression();
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRICT_EQ:
      case STRICT_NEQ:
      case EQ:
      case NEQ:
        ;
        break;
      default:
        jj_la1[51] = jj_gen;
        break label_16;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRICT_EQ:
        jj_consume_token(STRICT_EQ);
        break;
      case STRICT_NEQ:
        jj_consume_token(STRICT_NEQ);
        break;
      case EQ:
        jj_consume_token(EQ);
        break;
      case NEQ:
        jj_consume_token(NEQ);
        break;
      default:
        jj_la1[52] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      RelationalExpression();
    }
  }

  final public void RelationalExpression() throws ParseException {
    ShiftExpression();
    label_17:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INSTANCEOF:
      case IN:
      case LEQ:
      case GEQ:
      case LT:
      case GT:
        ;
        break;
      default:
        jj_la1[53] = jj_gen;
        break label_17;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LT:
        jj_consume_token(LT);
        break;
      case GT:
        jj_consume_token(GT);
        break;
      case LEQ:
        jj_consume_token(LEQ);
        break;
      case GEQ:
        jj_consume_token(GEQ);
        break;
      case INSTANCEOF:
        jj_consume_token(INSTANCEOF);
        break;
      case IN:
        jj_consume_token(IN);
        break;
      default:
        jj_la1[54] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      ShiftExpression();
    }
  }

  final public void ShiftExpression() throws ParseException {
    AdditiveExpression();
    label_18:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LSHIFT:
      case RSHIFT:
      case URSHIFT:
        ;
        break;
      default:
        jj_la1[55] = jj_gen;
        break label_18;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LSHIFT:
        jj_consume_token(LSHIFT);
        break;
      case RSHIFT:
        jj_consume_token(RSHIFT);
        break;
      case URSHIFT:
        jj_consume_token(URSHIFT);
        break;
      default:
        jj_la1[56] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      AdditiveExpression();
    }
  }

  final public void AdditiveExpression() throws ParseException {
    MultiplicativeExpression();
    label_19:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
        ;
        break;
      default:
        jj_la1[57] = jj_gen;
        break label_19;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        jj_consume_token(PLUS);
        break;
      case MINUS:
        jj_consume_token(MINUS);
        break;
      default:
        jj_la1[58] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      MultiplicativeExpression();
    }
  }

  final public void MultiplicativeExpression() throws ParseException {
    UnaryExpression();
    label_20:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TIMES:
      case DIV:
      case MOD:
        ;
        break;
      default:
        jj_la1[59] = jj_gen;
        break label_20;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TIMES:
        jj_consume_token(TIMES);
        break;
      case DIV:
        jj_consume_token(DIV);
        break;
      case MOD:
        jj_consume_token(MOD);
        break;
      default:
        jj_la1[60] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      UnaryExpression();
    }
  }

  final public void UnaryExpression() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TYPEOF:
    case DELETE:
    case VOID:
    case PLUS:
    case MINUS:
    case NOT:
    case TILDE:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NOT:
        jj_consume_token(NOT);
        break;
      case MINUS:
        jj_consume_token(MINUS);
        break;
      case PLUS:
        jj_consume_token(PLUS);
        break;
      case TILDE:
        jj_consume_token(TILDE);
        break;
      case TYPEOF:
        jj_consume_token(TYPEOF);
        break;
      case VOID:
        jj_consume_token(VOID);
        break;
      case DELETE:
        jj_consume_token(DELETE);
        break;
      default:
        jj_la1[61] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      UnaryExpression();
      break;
    case FUNCTION:
    case NEW:
    case THIS:
    case SUPER:
    case TRUE:
    case FALSE:
    case NULL:
    case UNDEFINED:
    case NUMBER:
    case STRING_DOUBLE:
    case STRING_SINGLE:
    case TEMPLATE_STR:
    case IDENTIFIER:
    case PLUSPLUS:
    case MINUSMINUS:
    case LPAREN:
    case LBRACE:
    case LBRACKET:
      PostfixExpression();
      break;
    default:
      jj_la1[62] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void PostfixExpression() throws ParseException {
    LeftHandSideExpression();
    if (jj_2_12(2)) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUSPLUS:
        jj_consume_token(PLUSPLUS);
        break;
      case MINUSMINUS:
        jj_consume_token(MINUSMINUS);
        break;
      default:
        jj_la1[63] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } else {
      ;
    }
  }

  final public void LeftHandSideExpression() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PLUSPLUS:
    case MINUSMINUS:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUSPLUS:
        jj_consume_token(PLUSPLUS);
        break;
      case MINUSMINUS:
        jj_consume_token(MINUSMINUS);
        break;
      default:
        jj_la1[64] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[65] = jj_gen;
      ;
    }
    PrimaryExpression();
    label_21:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUSPLUS:
      case MINUSMINUS:
      case OPT_CHAIN:
      case DOT:
      case LPAREN:
      case LBRACKET:
        ;
        break;
      default:
        jj_la1[66] = jj_gen;
        break label_21;
      }
      Suffix();
    }
  }

  final public void Suffix() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DOT:
      jj_consume_token(DOT);
      jj_consume_token(IDENTIFIER);
      break;
    case OPT_CHAIN:
      jj_consume_token(OPT_CHAIN);
      jj_consume_token(IDENTIFIER);
      break;
    case LBRACKET:
      jj_consume_token(LBRACKET);
      Expression();
      jj_consume_token(RBRACKET);
      break;
    case LPAREN:
      jj_consume_token(LPAREN);
      ArgumentList();
      jj_consume_token(RPAREN);
      break;
    case PLUSPLUS:
      jj_consume_token(PLUSPLUS);
      break;
    case MINUSMINUS:
      jj_consume_token(MINUSMINUS);
      break;
    default:
      jj_la1[67] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void ArgumentList() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FUNCTION:
    case NEW:
    case TYPEOF:
    case THIS:
    case SUPER:
    case DELETE:
    case VOID:
    case TRUE:
    case FALSE:
    case NULL:
    case UNDEFINED:
    case NUMBER:
    case STRING_DOUBLE:
    case STRING_SINGLE:
    case TEMPLATE_STR:
    case IDENTIFIER:
    case PLUSPLUS:
    case MINUSMINUS:
    case SPREAD:
    case PLUS:
    case MINUS:
    case NOT:
    case TILDE:
    case LPAREN:
    case LBRACE:
    case LBRACKET:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SPREAD:
        jj_consume_token(SPREAD);
        break;
      default:
        jj_la1[68] = jj_gen;
        ;
      }
      AssignmentExpression();
      label_22:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[69] = jj_gen;
          break label_22;
        }
        jj_consume_token(COMMA);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SPREAD:
          jj_consume_token(SPREAD);
          break;
        default:
          jj_la1[70] = jj_gen;
          ;
        }
        AssignmentExpression();
      }
      break;
    default:
      jj_la1[71] = jj_gen;
      ;
    }
  }

  final public void PrimaryExpression() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      t = jj_consume_token(IDENTIFIER);
      checkVarUse(t.image);
      break;
    case NUMBER:
      jj_consume_token(NUMBER);
      break;
    case STRING_DOUBLE:
      jj_consume_token(STRING_DOUBLE);
      break;
    case STRING_SINGLE:
      jj_consume_token(STRING_SINGLE);
      break;
    case TEMPLATE_STR:
      jj_consume_token(TEMPLATE_STR);
      break;
    case TRUE:
      jj_consume_token(TRUE);
      break;
    case FALSE:
      jj_consume_token(FALSE);
      break;
    case NULL:
      jj_consume_token(NULL);
      break;
    case UNDEFINED:
      jj_consume_token(UNDEFINED);
      break;
    case THIS:
      jj_consume_token(THIS);
      break;
    case SUPER:
      jj_consume_token(SUPER);
      break;
    case LBRACKET:
      ArrayLiteral();
      break;
    case LBRACE:
      ObjectLiteral();
      break;
    case NEW:
      jj_consume_token(NEW);
      Expression();
      break;
    case LPAREN:
      jj_consume_token(LPAREN);
      if (jj_2_13(2147483647)) {
        ArrowFunction();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case FUNCTION:
        case NEW:
        case TYPEOF:
        case THIS:
        case SUPER:
        case DELETE:
        case VOID:
        case TRUE:
        case FALSE:
        case NULL:
        case UNDEFINED:
        case NUMBER:
        case STRING_DOUBLE:
        case STRING_SINGLE:
        case TEMPLATE_STR:
        case IDENTIFIER:
        case PLUSPLUS:
        case MINUSMINUS:
        case PLUS:
        case MINUS:
        case NOT:
        case TILDE:
        case LPAREN:
        case LBRACE:
        case LBRACKET:
          Expression();
          break;
        default:
          jj_la1[72] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      jj_consume_token(RPAREN);
      break;
    case FUNCTION:
      FunctionExpression();
      break;
    default:
      jj_la1[73] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void FunctionExpression() throws ParseException {
  Token t;
    jj_consume_token(FUNCTION);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      t = jj_consume_token(IDENTIFIER);
        declareVar(t.image, "function");
      break;
    default:
      jj_la1[74] = jj_gen;
      ;
    }
    jj_consume_token(LPAREN);
      enterScope();
    FormalParameters();
    jj_consume_token(RPAREN);
    FunctionBlock();
      exitScope();
  }

  final public void ArrayLiteral() throws ParseException {
    jj_consume_token(LBRACKET);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FUNCTION:
    case NEW:
    case TYPEOF:
    case THIS:
    case SUPER:
    case DELETE:
    case VOID:
    case TRUE:
    case FALSE:
    case NULL:
    case UNDEFINED:
    case NUMBER:
    case STRING_DOUBLE:
    case STRING_SINGLE:
    case TEMPLATE_STR:
    case IDENTIFIER:
    case PLUSPLUS:
    case MINUSMINUS:
    case SPREAD:
    case PLUS:
    case MINUS:
    case NOT:
    case TILDE:
    case LPAREN:
    case LBRACE:
    case LBRACKET:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SPREAD:
        jj_consume_token(SPREAD);
        break;
      default:
        jj_la1[75] = jj_gen;
        ;
      }
      AssignmentExpression();
      label_23:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[76] = jj_gen;
          break label_23;
        }
        jj_consume_token(COMMA);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case FUNCTION:
        case NEW:
        case TYPEOF:
        case THIS:
        case SUPER:
        case DELETE:
        case VOID:
        case TRUE:
        case FALSE:
        case NULL:
        case UNDEFINED:
        case NUMBER:
        case STRING_DOUBLE:
        case STRING_SINGLE:
        case TEMPLATE_STR:
        case IDENTIFIER:
        case PLUSPLUS:
        case MINUSMINUS:
        case SPREAD:
        case PLUS:
        case MINUS:
        case NOT:
        case TILDE:
        case LPAREN:
        case LBRACE:
        case LBRACKET:
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case SPREAD:
            jj_consume_token(SPREAD);
            break;
          default:
            jj_la1[77] = jj_gen;
            ;
          }
          AssignmentExpression();
          break;
        default:
          jj_la1[78] = jj_gen;
          ;
        }
      }
      break;
    default:
      jj_la1[79] = jj_gen;
      ;
    }
    jj_consume_token(RBRACKET);
  }

  final public void ObjectLiteral() throws ParseException {
    jj_consume_token(LBRACE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMBER:
    case STRING_DOUBLE:
    case STRING_SINGLE:
    case IDENTIFIER:
    case SPREAD:
      ObjectProperty();
      label_24:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[80] = jj_gen;
          break label_24;
        }
        jj_consume_token(COMMA);
        ObjectProperty();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        jj_consume_token(COMMA);
        break;
      default:
        jj_la1[81] = jj_gen;
        ;
      }
      break;
    default:
      jj_la1[82] = jj_gen;
      ;
    }
    jj_consume_token(RBRACE);
  }

  final public void ObjectProperty() throws ParseException {
  Token t;
    if (jj_2_14(2147483647)) {
      jj_consume_token(SPREAD);
      AssignmentExpression();
    } else if (jj_2_15(2147483647)) {
      t = jj_consume_token(IDENTIFIER);
      jj_consume_token(LPAREN);
      enterScope();
      FormalParameters();
      jj_consume_token(RPAREN);
      FunctionBlock();
      exitScope();
    } else if (jj_2_16(2147483647)) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        t = jj_consume_token(IDENTIFIER);
        break;
      case STRING_DOUBLE:
        t = jj_consume_token(STRING_DOUBLE);
        break;
      case STRING_SINGLE:
        t = jj_consume_token(STRING_SINGLE);
        break;
      case NUMBER:
        t = jj_consume_token(NUMBER);
        break;
      default:
        jj_la1[83] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(COLON);
      AssignmentExpression();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        t = jj_consume_token(IDENTIFIER);
      checkVarUse(t.image);
        break;
      default:
        jj_la1[84] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_3R_72() {
    if (jj_3R_79()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_149()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_148() {
    if (jj_3R_157()) return true;
    return false;
  }

  private boolean jj_3R_147() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(82)) {
    jj_scanpos = xsp;
    if (jj_scan_token(78)) {
    jj_scanpos = xsp;
    if (jj_scan_token(77)) {
    jj_scanpos = xsp;
    if (jj_scan_token(83)) {
    jj_scanpos = xsp;
    if (jj_scan_token(24)) {
    jj_scanpos = xsp;
    if (jj_scan_token(40)) {
    jj_scanpos = xsp;
    if (jj_scan_token(39)) return true;
    }
    }
    }
    }
    }
    }
    if (jj_3R_136()) return true;
    return false;
  }

  private boolean jj_3R_136() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_147()) {
    jj_scanpos = xsp;
    if (jj_3R_148()) return true;
    }
    return false;
  }

  private boolean jj_3R_137() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(79)) {
    jj_scanpos = xsp;
    if (jj_scan_token(80)) {
    jj_scanpos = xsp;
    if (jj_scan_token(81)) return true;
    }
    }
    if (jj_3R_136()) return true;
    return false;
  }

  private boolean jj_3R_51() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(8)) {
    jj_scanpos = xsp;
    if (jj_scan_token(9)) {
    jj_scanpos = xsp;
    if (jj_scan_token(10)) return true;
    }
    }
    if (jj_3R_72()) return true;
    xsp = jj_scanpos;
    if (jj_scan_token(89)) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_132() {
    if (jj_3R_136()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_137()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_133() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(77)) {
    jj_scanpos = xsp;
    if (jj_scan_token(78)) return true;
    }
    if (jj_3R_132()) return true;
    return false;
  }

  private boolean jj_3R_127() {
    if (jj_3R_132()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_133()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_118() {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_128() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(63)) {
    jj_scanpos = xsp;
    if (jj_scan_token(64)) {
    jj_scanpos = xsp;
    if (jj_scan_token(65)) return true;
    }
    }
    if (jj_3R_127()) return true;
    return false;
  }

  private boolean jj_3R_112() {
    if (jj_scan_token(LBRACE)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_118()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3R_120() {
    if (jj_3R_127()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_128()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_121() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(75)) {
    jj_scanpos = xsp;
    if (jj_scan_token(76)) {
    jj_scanpos = xsp;
    if (jj_scan_token(66)) {
    jj_scanpos = xsp;
    if (jj_scan_token(67)) {
    jj_scanpos = xsp;
    if (jj_scan_token(25)) {
    jj_scanpos = xsp;
    if (jj_scan_token(26)) return true;
    }
    }
    }
    }
    }
    if (jj_3R_120()) return true;
    return false;
  }

  private boolean jj_3R_71() {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_116() {
    if (jj_3R_120()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_121()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_scan_token(LBRACE)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_71()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3R_117() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(50)) {
    jj_scanpos = xsp;
    if (jj_scan_token(51)) {
    jj_scanpos = xsp;
    if (jj_scan_token(52)) {
    jj_scanpos = xsp;
    if (jj_scan_token(53)) return true;
    }
    }
    }
    if (jj_3R_116()) return true;
    return false;
  }

  private boolean jj_3R_110() {
    if (jj_3R_116()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_117()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_3R_64()) return true;
    return false;
  }

  private boolean jj_3R_111() {
    if (jj_scan_token(AMP)) return true;
    if (jj_3R_110()) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_3R_63()) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_scan_token(FUNCTION)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_3R_62()) return true;
    return false;
  }

  private boolean jj_3R_97() {
    if (jj_3R_110()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_111()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_3R_61()) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_3R_60()) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_3R_59()) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_3R_58()) return true;
    return false;
  }

  private boolean jj_3R_98() {
    if (jj_scan_token(CARET)) return true;
    if (jj_3R_97()) return true;
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_3R_57()) return true;
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_3R_56()) return true;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_3R_55()) return true;
    return false;
  }

  private boolean jj_3R_87() {
    if (jj_3R_97()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_98()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_3R_54()) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_3R_53()) return true;
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_3R_52()) return true;
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_3R_51()) return true;
    return false;
  }

  private boolean jj_3R_88() {
    if (jj_scan_token(PIPE)) return true;
    if (jj_3R_87()) return true;
    return false;
  }

  private boolean jj_3R_26() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) {
    jj_scanpos = xsp;
    if (jj_scan_token(89)) {
    jj_scanpos = xsp;
    if (jj_3R_45()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_3R_50()) return true;
    return false;
  }

  private boolean jj_3R_77() {
    if (jj_3R_87()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_88()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_78() {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_69() {
    if (jj_3R_77()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_78()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_70() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(69)) {
    jj_scanpos = xsp;
    if (jj_scan_token(70)) return true;
    }
    if (jj_3R_69()) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_3R_69()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_70()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_scan_token(QUESTION)) return true;
    if (jj_3R_46()) return true;
    if (jj_scan_token(COLON)) return true;
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_3R_48()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_49()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_30() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(74)) {
    jj_scanpos = xsp;
    if (jj_scan_token(56)) {
    jj_scanpos = xsp;
    if (jj_scan_token(57)) {
    jj_scanpos = xsp;
    if (jj_scan_token(58)) {
    jj_scanpos = xsp;
    if (jj_scan_token(59)) {
    jj_scanpos = xsp;
    if (jj_scan_token(60)) {
    jj_scanpos = xsp;
    if (jj_scan_token(61)) {
    jj_scanpos = xsp;
    if (jj_scan_token(62)) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_100() {
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3R_99() {
    if (jj_3R_112()) return true;
    return false;
  }

  private boolean jj_3R_81() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_68()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_74() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(49)) {
    jj_scanpos = xsp;
    if (jj_3R_81()) return true;
    }
    if (jj_scan_token(ARROW)) return true;
    xsp = jj_scanpos;
    if (jj_3R_99()) {
    jj_scanpos = xsp;
    if (jj_3R_100()) return true;
    }
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_68()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_3R_29()) return true;
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3R_28() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(49)) {
    jj_scanpos = xsp;
    if (jj_3R_47()) return true;
    }
    return false;
  }

  private boolean jj_3_10() {
    if (jj_3R_28()) return true;
    if (jj_scan_token(ARROW)) return true;
    return false;
  }

  private boolean jj_3R_67() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3R_66() {
    if (jj_3R_75()) return true;
    if (jj_3R_30()) return true;
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3R_65() {
    if (jj_3R_74()) return true;
    return false;
  }

  private boolean jj_3R_46() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_65()) {
    jj_scanpos = xsp;
    if (jj_3R_66()) {
    jj_scanpos = xsp;
    if (jj_3R_67()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3R_80() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_73() {
    if (jj_3R_27()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_80()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_64() {
    if (jj_3R_73()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(89)) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_63() {
    if (jj_scan_token(THROW)) return true;
    if (jj_3R_27()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(89)) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_62() {
    if (jj_scan_token(CONTINUE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(49)) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(89)) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_61() {
    if (jj_scan_token(BREAK)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(49)) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(89)) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_60() {
    if (jj_scan_token(RETURN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_7()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(89)) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_146() {
    if (jj_scan_token(FINALLY)) return true;
    if (jj_3R_50()) return true;
    return false;
  }

  private boolean jj_3R_156() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_145() {
    if (jj_scan_token(CATCH)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_156()) jj_scanpos = xsp;
    if (jj_3R_50()) return true;
    return false;
  }

  private boolean jj_3R_59() {
    if (jj_scan_token(TRY)) return true;
    if (jj_3R_50()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_145()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_146()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_155() {
    if (jj_scan_token(JS_DEFAULT)) return true;
    if (jj_scan_token(COLON)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_6()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_154() {
    if (jj_scan_token(CASE)) return true;
    if (jj_3R_27()) return true;
    if (jj_scan_token(COLON)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_5()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_144() {
    if (jj_3R_155()) return true;
    return false;
  }

  private boolean jj_3R_143() {
    if (jj_3R_154()) return true;
    return false;
  }

  private boolean jj_3_4() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(8)) {
    jj_scanpos = xsp;
    if (jj_scan_token(9)) {
    jj_scanpos = xsp;
    if (jj_scan_token(10)) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_scan_token(SWITCH)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_27()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_scan_token(LBRACE)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_143()) { jj_scanpos = xsp; break; }
    }
    xsp = jj_scanpos;
    if (jj_3R_144()) jj_scanpos = xsp;
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3R_165() {
    if (jj_3R_73()) return true;
    return false;
  }

  private boolean jj_3R_163() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_165()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_162() {
    if (jj_3R_164()) return true;
    return false;
  }

  private boolean jj_3R_151() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_162()) {
    jj_scanpos = xsp;
    if (jj_3R_163()) return true;
    }
    return false;
  }

  private boolean jj_3R_164() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(8)) {
    jj_scanpos = xsp;
    if (jj_scan_token(9)) {
    jj_scanpos = xsp;
    if (jj_scan_token(10)) return true;
    }
    }
    if (jj_3R_72()) return true;
    return false;
  }

  private boolean jj_3R_25() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(8)) {
    jj_scanpos = xsp;
    if (jj_scan_token(9)) {
    jj_scanpos = xsp;
    if (jj_scan_token(10)) return true;
    }
    }
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_25()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(26)) {
    jj_scanpos = xsp;
    if (jj_scan_token(27)) return true;
    }
    return false;
  }

  private boolean jj_3_16() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(49)) {
    jj_scanpos = xsp;
    if (jj_scan_token(46)) {
    jj_scanpos = xsp;
    if (jj_scan_token(47)) {
    jj_scanpos = xsp;
    if (jj_scan_token(45)) return true;
    }
    }
    }
    if (jj_scan_token(COLON)) return true;
    return false;
  }

  private boolean jj_3R_153() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_152() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_126() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_142() {
    if (jj_3R_151()) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_152()) jj_scanpos = xsp;
    if (jj_scan_token(SEMICOLON)) return true;
    xsp = jj_scanpos;
    if (jj_3R_153()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_15() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_141() {
    if (jj_3R_25()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(26)) {
    jj_scanpos = xsp;
    if (jj_scan_token(27)) return true;
    }
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_125() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(49)) {
    jj_scanpos = xsp;
    if (jj_scan_token(46)) {
    jj_scanpos = xsp;
    if (jj_scan_token(47)) {
    jj_scanpos = xsp;
    if (jj_scan_token(45)) return true;
    }
    }
    }
    if (jj_scan_token(COLON)) return true;
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3_14() {
    if (jj_scan_token(SPREAD)) return true;
    return false;
  }

  private boolean jj_3R_57() {
    if (jj_scan_token(FOR)) return true;
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_141()) {
    jj_scanpos = xsp;
    if (jj_3R_142()) return true;
    }
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_124() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_68()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_112()) return true;
    return false;
  }

  private boolean jj_3R_119() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_123()) {
    jj_scanpos = xsp;
    if (jj_3R_124()) {
    jj_scanpos = xsp;
    if (jj_3R_125()) {
    jj_scanpos = xsp;
    if (jj_3R_126()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_123() {
    if (jj_scan_token(SPREAD)) return true;
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_scan_token(DO)) return true;
    if (jj_3R_26()) return true;
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_27()) return true;
    if (jj_scan_token(RPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(89)) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_134() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(72)) jj_scanpos = xsp;
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3R_130() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_119()) return true;
    return false;
  }

  private boolean jj_3R_114() {
    if (jj_3R_119()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_130()) { jj_scanpos = xsp; break; }
    }
    xsp = jj_scanpos;
    if (jj_scan_token(90)) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_27()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_102() {
    if (jj_scan_token(LBRACE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_114()) jj_scanpos = xsp;
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3R_129() {
    if (jj_scan_token(COMMA)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_134()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_140() {
    if (jj_scan_token(ELSE)) return true;
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_113() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(72)) jj_scanpos = xsp;
    if (jj_3R_46()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_129()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_27()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_26()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_140()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_101() {
    if (jj_scan_token(LBRACKET)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_113()) jj_scanpos = xsp;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  private boolean jj_3R_161() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(99)) jj_scanpos = xsp;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_68()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_112()) return true;
    return false;
  }

  private boolean jj_3R_159() {
    return false;
  }

  private boolean jj_3R_115() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_3R_28()) return true;
    if (jj_scan_token(ARROW)) return true;
    return false;
  }

  private boolean jj_3R_160() {
    if (jj_scan_token(98)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_68()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_112()) return true;
    return false;
  }

  private boolean jj_3R_105() {
    if (jj_scan_token(FUNCTION)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_115()) jj_scanpos = xsp;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_68()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_112()) return true;
    return false;
  }

  private boolean jj_3R_104() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_94() {
    if (jj_3R_105()) return true;
    return false;
  }

  private boolean jj_3R_150() {
    if (jj_3R_159()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_160()) {
    jj_scanpos = xsp;
    if (jj_3R_161()) return true;
    }
    return false;
  }

  private boolean jj_3R_103() {
    if (jj_3R_74()) return true;
    return false;
  }

  private boolean jj_3R_139() {
    if (jj_3R_150()) return true;
    return false;
  }

  private boolean jj_3R_93() {
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_103()) {
    jj_scanpos = xsp;
    if (jj_3R_104()) return true;
    }
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_92() {
    if (jj_scan_token(NEW)) return true;
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_138() {
    if (jj_scan_token(EXTENDS)) return true;
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_91() {
    if (jj_3R_102()) return true;
    return false;
  }

  private boolean jj_3R_90() {
    if (jj_3R_101()) return true;
    return false;
  }

  private boolean jj_3R_53() {
    if (jj_scan_token(CLASS)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_138()) jj_scanpos = xsp;
    if (jj_scan_token(LBRACE)) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_139()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3R_96() {
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3R_86() {
    if (jj_scan_token(COMMA)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(72)) jj_scanpos = xsp;
    if (jj_scan_token(IDENTIFIER)) return true;
    xsp = jj_scanpos;
    if (jj_3R_96()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_85() {
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3R_83() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_89()) {
    jj_scanpos = xsp;
    if (jj_scan_token(45)) {
    jj_scanpos = xsp;
    if (jj_scan_token(46)) {
    jj_scanpos = xsp;
    if (jj_scan_token(47)) {
    jj_scanpos = xsp;
    if (jj_scan_token(48)) {
    jj_scanpos = xsp;
    if (jj_scan_token(41)) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) {
    jj_scanpos = xsp;
    if (jj_scan_token(43)) {
    jj_scanpos = xsp;
    if (jj_scan_token(44)) {
    jj_scanpos = xsp;
    if (jj_scan_token(30)) {
    jj_scanpos = xsp;
    if (jj_scan_token(31)) {
    jj_scanpos = xsp;
    if (jj_3R_90()) {
    jj_scanpos = xsp;
    if (jj_3R_91()) {
    jj_scanpos = xsp;
    if (jj_3R_92()) {
    jj_scanpos = xsp;
    if (jj_3R_93()) {
    jj_scanpos = xsp;
    if (jj_3R_94()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_89() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_135() {
    if (jj_scan_token(COMMA)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(72)) jj_scanpos = xsp;
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3R_76() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(72)) jj_scanpos = xsp;
    if (jj_scan_token(IDENTIFIER)) return true;
    xsp = jj_scanpos;
    if (jj_3R_85()) jj_scanpos = xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_86()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_131() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(72)) jj_scanpos = xsp;
    if (jj_3R_46()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_135()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_68() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_76()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_122() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_131()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_109() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_122()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_108() {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_3R_27()) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  private boolean jj_3R_107() {
    if (jj_scan_token(OPT_CHAIN)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_95() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_106()) {
    jj_scanpos = xsp;
    if (jj_3R_107()) {
    jj_scanpos = xsp;
    if (jj_3R_108()) {
    jj_scanpos = xsp;
    if (jj_3R_109()) {
    jj_scanpos = xsp;
    if (jj_scan_token(54)) {
    jj_scanpos = xsp;
    if (jj_scan_token(55)) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_106() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_scan_token(FUNCTION)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_68()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_112()) return true;
    return false;
  }

  private boolean jj_3R_84() {
    if (jj_3R_95()) return true;
    return false;
  }

  private boolean jj_3R_82() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(54)) {
    jj_scanpos = xsp;
    if (jj_scan_token(55)) return true;
    }
    return false;
  }

  private boolean jj_3R_75() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_82()) jj_scanpos = xsp;
    if (jj_3R_83()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_84()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_158() {
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(54)) {
    jj_scanpos = xsp;
    if (jj_scan_token(55)) return true;
    }
    return false;
  }

  private boolean jj_3R_79() {
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_158()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_157() {
    if (jj_3R_75()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_12()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_149() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_79()) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(0)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public JavaScriptTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  /** Whether we are looking ahead. */
  private boolean jj_lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[85];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
      jj_la1_init_3();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xd19fbf00,0x700,0xd19fb800,0xd19fbf00,0xd19fbf00,0x700,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x20000000,0x0,0x0,0x0,0x4000,0x0,0xc000000,0xc1800800,0xc1800800,0xc1800f00,0x700,0x700,0xc1800800,0x200000,0x400000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xc1800800,0x0,0x0,0xc1800800,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x6000000,0x6000000,0x0,0x0,0x0,0x0,0x0,0x0,0x1000000,0xc1800800,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xc1800800,0xc1800800,0xc0800800,0x0,0x0,0x0,0x0,0xc1800800,0xc1800800,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0xc3ffc8,0x0,0xc3ffc8,0xc3ffc8,0xc3ffc8,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x20000,0x0,0x20000,0x0,0x20000,0x0,0x0,0x0,0xc3ff80,0xc3ff80,0xc3ff80,0x0,0x0,0xc3ff80,0x0,0x0,0x0,0x10,0x20,0x0,0x0,0x0,0x0,0x0,0x0,0xc3ff80,0x20000,0x20000,0xc3ff80,0x7f000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x3c0000,0x3c0000,0x0,0x0,0x80000000,0x80000000,0x0,0x0,0x0,0x0,0x180,0xc3ff80,0xc00000,0xc00000,0xc00000,0xc00000,0xc00000,0x0,0x0,0x0,0xc3ff80,0xc3ff80,0x3fe00,0x20000,0x0,0x0,0x0,0xc3ff80,0xc3ff80,0x0,0x0,0x2e000,0x2e000,0x20000,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x520c6000,0x40000000,0x520c6000,0x520c6000,0x520c6000,0x0,0x2000000,0x4000000,0x400,0x100,0x400,0x4000000,0x100,0x400,0x100,0x0,0x0,0x0,0x0,0x0,0x2000000,0x0,0x500c6000,0x500c6000,0x520c6000,0x0,0x0,0x500c6000,0x0,0x0,0x10000000,0x0,0x0,0x2000000,0x2000000,0x2000000,0x2000000,0x2000000,0x4000000,0x500c6000,0x10000000,0x10000000,0x500c6000,0x400,0x800000,0x60,0x60,0x10,0x200000,0x400000,0x100000,0x0,0x0,0x180c,0x180c,0x3,0x3,0x6000,0x6000,0x38000,0x38000,0xc6000,0x500c6000,0x0,0x0,0x0,0x18000200,0x18000200,0x100,0x4000000,0x100,0x500c6100,0x500c6000,0x50000000,0x0,0x100,0x4000000,0x100,0x500c6100,0x500c6100,0x4000000,0x4000000,0x100,0x0,0x0,};
   }
   private static void jj_la1_init_3() {
      jj_la1_3 = new int[] {0x1,0x0,0x1,0x1,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xc,0x8,0xc,0x0,0x0,0x0,0x1,0x1,0x1,0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x1,0x1,0x0,0x0,0x0,0x1,0x1,0x1,0x0,0x0,0x0,0x0,0x1,0x1,0x0,0x0,0x0,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[16];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public JavaScript(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public JavaScript(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new JavaScriptTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 85; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 85; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public JavaScript(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new JavaScriptTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 85; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 85; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public JavaScript(JavaScriptTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 85; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(JavaScriptTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 85; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = jj_lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[100];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 85; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 100; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 16; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
